-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 10:44:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clases
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clases` ;

-- -----------------------------------------------------
-- Schema clases
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clases` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `clases` ;

-- -----------------------------------------------------
-- Table `Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empresa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Empresa` (
  `cif` INT NOT NULL,
  `nombre` VARCHAR(25) NULL,
  `dirección` VARCHAR(50) NULL,
  `telefono` CHAR(9) NULL,
  PRIMARY KEY (`cif`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alumnos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `alumnos` (
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellido1` VARCHAR(25) NOT NULL,
  `apellido2` VARCHAR(25) NOT NULL,
  `dirección` VARCHAR(50) NULL,
  `telefono` CHAR(9) NULL,
  `edad` NCHAR(2) NULL,
  `cif` VARCHAR(9) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `asistir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asistir` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `asistir` (
  `dni` VARCHAR(9) NOT NULL,
  `n_curso` NCHAR(3) NOT NULL,
  `nota` FLOAT NULL,
  PRIMARY KEY (`dni`, `n_curso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cursos` (
  `n_curso` INT NOT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `cod_curso` CHAR(8) NULL,
  `dni_profesor` VARCHAR(9) NULL,
  PRIMARY KEY (`n_curso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profesor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `profesor` (
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido1` VARCHAR(50) NOT NULL,
  `apellido2` VARCHAR(50) NOT NULL,
  `dirección` VARCHAR(50) NULL,
  `telefono` CHAR(9) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipos_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipos_curso` (
  `cod_curso` CHAR(8) NOT NULL,
  `titulo` VARCHAR(50) NULL,
  `duracion` INT NULL,
  PRIMARY KEY (`cod_curso`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
